### ISSUE TITLE
Problem on dtypes when extractin poprock corpus

### ISSUE THREAD

**Issue by bichomartiano** [DIDONEproject/musiF#44]
UndefinedvariableError. 'NA' is not defined. Erro when extracting features on the pop rock corpus

**Comment by 00sapo** [comment]
Thanks Martin! `'NA'` should be converted into [`pd.NA`](https://pandas.pydata.org/docs/user_guide/missing_data.html#experimental-na-scalar-to-denote-missing-values) in this lines:

https://github.com/DIDONEproject/musiF/blob/8fa7786b14967702ed412f34cbc50ee8187493df/musif/extract/extract.py#L312-L324

Could you check it?

It looks like for some reason it's re-converted to string `"NA"`, maybe because of the `__reduce__` method of `pd.NA`: 

https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/missing.pyx#L420

If this is the case, we should find another method to cast all the strings "NA" to `pd.NA`. Another solution is to modify [`cast_mixed_types`](https://github.com/DIDONEproject/musiF/blob/main/musif/extract/utils.py#L570) like this:

```
        if issubclass(newtype, float):
            # new line: convert nans:
            col = col.replace("NA", np.nan")
            #  convert fractions like '1/3' to float
            col[notna] = col[notna].apply(pd.eval)
            col = col.convert_dtypes()
         
```

**Comment by bichomartiano** [comment]
Ok! indeed, for some reason I didn't have line 323, so it wasn't being replaced. A version problem I guess.
Now it works fine, lets thing on mergin on develop everything soon.
