### ISSUE TITLE
musif not able to process jsymbolic features when using cache

### ISSUE THREAD

**Issue by martianbug** [DIDONEproject/musif#62]
I'm getting an error trying to extract features when jsymbolic is selected and the cache is activated. The error is in line 398 of extract.py: Exception has occurred: TypeError
cannot pickle 'weakref.ReferenceType' object

Also, it seems that jsymbolic has difficulties to process this file (as well as few others)
jSymbolic: could not convert data/xml_half/Ale01M-E_prezzo-1731-Handel[1.01][0958].xml to MIDI: cannot expand Stream: badly formed repeats or repeat expressions.

I'll paste here my config.yml file currently:
metadata_dir: ./metadata
xml_dir: data/xml
musescore_dir: data/musescore
cache_dir: data/cache
expand_repeats: false
window_size: null
overlap: 2
internal_data_dir: ./internal_data # custom config

parallel: 1
log:
  file_path: logs/musif_test.log
  file_level: INFO
  console_level: INFO
basic_modules_addresses: ["feature_extraction.custom_basic_modules", "musif.extract.basic_modules"]

feature_modules_addresses: 
  - "musif.extract.features"
  - "feature_extraction.custom_features"
  - "feature_extraction.custom_features_module"

basic_modules:
  - scoring
  - file_name # custom feature
  - metadata # custom feature
  - composer # custom feature
  - librettist # custom feature

features:
  - core
  - ambitus
  - melody
  - tempo
  - density
  - texture
  - lyrics
  - scale
  - key
  - dynamics    
  - rhythm  
  - harmony
  - scale_relative
  - music21
  - jsymbolic
  

split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - guitar
  - brass
  - wind
  - viola
  - strings.cello
  - bass
  - oboi
  
parts_filter:
  # - vnI

**Comment by 00sapo** [comment]
So, for the first problem, the issue is with repeats, and it is likely not due to musif. The call to `fix_repeats` in `extract.py` should solve it. If it is not solved yet, try debugging it.

For the main issue about jsymbolic and cache, the problem is that we call the `write()` method of `music21.stream.Stream`, which returns nothing, just writes to disk. Since the cache works in an input/output basis, we cannot cache the writing operation. The solution is to use [this method](https://web.mit.edu/music21/doc/moduleReference/moduleConverter.html#music21.converter.toData) which returns a byte string and then write it to file with standard python libraries. Under the hood it seems that it will write to data twice, but this is a problem of music21 that is not splitting the conversation process in twice. Anyway, the code should look like this:

```python
from music21 import converter

s = converter.parse(myfilepath)

# attach a method to convert it into bytestring
# the first argument if toData is the object to be translated, so that could the `self` of a class method, perfectly ok
s.toData = converter.toData

# activate caching
cached_object = SmartModuleCache(s)

# get bytes
bytes = s.toData('midi')

# write to file
with open('output.mid', 'wb') as f:
    f.write(bytes)
```

**Comment by 00sapo** [comment]
Yeah, just before initializing the `SmartCacheModule`

**Comment by 00sapo** [comment]
We solved it, but we need to upgrade music21 to version 9 in `pyproject.toml`

**Comment by martianbug** [comment]
5dd7879c6b2b5be1a9bb3ea73f5a5a577f693fc3 updates pyproject.toml
